import { id } from "@/lib/id";
import type {
  CalibrationBand,
  Decision,
  FounderPattern,
  Prediction,
  PredictionDomain,
} from "@/lib/types";

const DOMAINS: PredictionDomain[] = [
  "growth",
  "revenue",
  "timeline",
  "technical",
  "retention",
  "distribution",
  "other",
];

export const DOMAIN_LABEL: Record<PredictionDomain, string> = {
  growth: "Growth estimates",
  revenue: "Revenue estimates",
  timeline: "Timeline estimates",
  technical: "Technical estimates",
  retention: "Retention estimates",
  distribution: "Distribution estimates",
  other: "Other estimates",
};

function evaluated(predictions: Prediction[]): Prediction[] {
  return predictions.filter(
    (p) => p.status !== "pending" && typeof p.ratio === "number",
  );
}

/**
 * Accuracy for a single prediction: 100 when the founder was exactly right,
 * decaying as the expected/actual ratio moves away from 1 in either direction.
 * Being 2x over and 2x under are penalised equally.
 */
function accuracyOf(prediction: Prediction): number {
  const ratio = prediction.ratio ?? 1;
  const normalised = ratio >= 1 ? ratio : 1 / ratio;
  return Math.max(0, Math.round(100 - (normalised - 1) * 60));
}

export function calibrationBands(predictions: Prediction[]): CalibrationBand[] {
  const done = evaluated(predictions);
  return DOMAINS.map((domain) => {
    const inDomain = done.filter((p) => p.domain === domain);
    if (inDomain.length === 0) {
      return { domain, accuracy: 0, sampleSize: 0, meanRatio: null };
    }
    const accuracy = Math.round(
      inDomain.reduce((sum, p) => sum + accuracyOf(p), 0) / inDomain.length,
    );
    const meanRatio =
      inDomain.reduce((sum, p) => sum + (p.ratio ?? 1), 0) / inDomain.length;
    return {
      domain,
      accuracy,
      sampleSize: inDomain.length,
      meanRatio: Number(meanRatio.toFixed(2)),
    };
  }).filter((band) => band.sampleSize > 0);
}

/**
 * Patterns are computed arithmetically rather than generated by a model.
 * A calibration warning is only credible if the founder can check the maths,
 * so every insight here is traceable to counted predictions.
 */
export function detectPatterns(
  companyId: string,
  predictions: Prediction[],
  decisions: Decision[],
): FounderPattern[] {
  const patterns: FounderPattern[] = [];
  const done = evaluated(predictions);

  for (const domain of DOMAINS) {
    const inDomain = done.filter((p) => p.domain === domain);
    if (inDomain.length < 2) continue;

    const ratios = inDomain.map((p) => p.ratio ?? 1);
    const mean = ratios.reduce((a, b) => a + b, 0) / ratios.length;
    const over = inDomain.filter((p) => (p.ratio ?? 1) > 1.15);
    const under = inDomain.filter((p) => (p.ratio ?? 1) < 0.85);
    const label = DOMAIN_LABEL[domain].replace(" estimates", "").toLowerCase();
    const decisionIds = inDomain.map((p) => p.decisionId);
    const confidence = Math.min(95, 45 + inDomain.length * 12);

    if (over.length >= 2 && mean > 1.25) {
      patterns.push({
        id: id("pat"),
        companyId,
        domain,
        insight: `You overestimated ${label} in ${over.length} of ${inDomain.length} predictions, by an average of ${mean.toFixed(1)}×.`,
        confidence,
        magnitude: Number(mean.toFixed(2)),
        sampleSize: inDomain.length,
        decisionIds,
        detectedAt: new Date().toISOString(),
      });
    } else if (under.length >= 2 && mean < 0.8) {
      patterns.push({
        id: id("pat"),
        companyId,
        domain,
        insight: `You underestimated ${label} in ${under.length} of ${inDomain.length} predictions, by an average of ${(1 / mean).toFixed(1)}×.`,
        confidence,
        magnitude: Number(mean.toFixed(2)),
        sampleSize: inDomain.length,
        decisionIds,
        detectedAt: new Date().toISOString(),
      });
    } else if (inDomain.length >= 3) {
      const accuracy = Math.round(
        inDomain.reduce((sum, p) => sum + accuracyOf(p), 0) / inDomain.length,
      );
      if (accuracy >= 78) {
        patterns.push({
          id: id("pat"),
          companyId,
          domain,
          insight: `Your ${label} predictions are reliable — ${accuracy}% accurate across ${inDomain.length} outcomes. Weight them heavily.`,
          confidence,
          magnitude: Number(mean.toFixed(2)),
          sampleSize: inDomain.length,
          decisionIds,
          detectedAt: new Date().toISOString(),
        });
      }
    }
  }

  const deferred = decisions.filter(
    (d) => d.status === "investigating" || d.status === "abandoned",
  );
  if (deferred.length >= 2) {
    patterns.push({
      id: id("pat"),
      companyId,
      domain: "commitment",
      insight: `You left ${deferred.length} decisions unresolved rather than committing. Deferral is itself a decision with a cost.`,
      confidence: Math.min(90, 40 + deferred.length * 15),
      sampleSize: deferred.length,
      decisionIds: deferred.map((d) => d.id),
      detectedAt: new Date().toISOString(),
    });
  }

  return patterns;
}

/**
 * The sentence the Arena puts in front of the founder while they are typing a
 * new prediction, when history says the number is likely to be optimistic.
 */
export function calibrationWarning(
  domain: PredictionDomain,
  expectedValue: number,
  patterns: FounderPattern[],
): { insight: string; adjusted: number; magnitude: number } | null {
  const pattern = patterns.find(
    (p) => p.domain === domain && (p.magnitude ?? 1) > 1.25,
  );
  if (!pattern || !pattern.magnitude) return null;
  return {
    insight: pattern.insight,
    adjusted: Math.round(expectedValue / pattern.magnitude),
    magnitude: pattern.magnitude,
  };
}
